/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AlertsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "InventoryApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "InventoryHistoryTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "InventoryTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "InventoryWeb": {
      "type": "sst.aws.React"
      "url": string
    }
    "ProductImagesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ProductsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}